theme: minima

title: APCSP Study Guide
author: Nikhil Tokala
description: AP® Computer Science Principles (APCSP) study guide for the AP® test. AP® is a trademark registered by the College Board, which is not affiliated with, and does not endorse, this site.

github_username: ntokala
url: ""

plugins: 
  - jemoji
  - jekyll-mentions

markdown: kramdown
kramdown:
   math_engine: mathjax
   syntax_highlighter: rouge



